### PR TITLE
Added restart button and fixed some bugs

### PR DESCRIPTION
**Pull request by msohcw**
Hi Colin. I'm in your 61A discussion. I noticed that you made this and had Restart button as an active issue so I added the functionality. Also fixed a bug with `clearInterval(gui.interval)`, needed to bind `this` to the function call otherwise `this` would be the global window.

### CODE REVIEW

**Review by colinschoen — COMMENTED** [review]
This is awesome. Thanks! I'll review tomorrow.

**Comment by msohcw** [comment]
Didn't test enough. Fixed the gui_ants.py so the hooks get added every time a game starts. Also standardised `GUI.update` to use `this` instead of the global `gui`.

**Comment by colinschoen** [comment]
Are you getting an AttributeError after `startGame` and on `getState`?

> File "gui.py", line 273, in do_POST
>     response = action(data)
>   File "gui.py", line 117, in getState
>     return self.state.getState()
> AttributeError: 'GUI' object has no attribute 'state'

**Comment by msohcw** [comment]
I saw that, but it was a heisenbug. The only reliable way I had to replicate it was to start `gui.py`, start a game, kill `gui.py` and then start `gui.py` again. The leftover windows sending POST requests when the Python server doesn't have a state yet causes the error. I could add a clause to the `do_POST` function. Is that the bug you're seeing though? Or does it error straight away on starting `gui.py`?

**Comment by colinschoen** [comment]
It is happening straight away when starting gui.py

**Comment by msohcw** [comment]
Do you have multiple Ants Web Viewer windows open?

**Comment by colinschoen** [comment]
Nope, only one window. I can do some debugging later today too.

**Comment by msohcw** [comment]
Might be a timing thing. I reordered it so that the GUI calls `cleanState` in `__init__` (as it previously was) and so that it calls `cleanState` before `reload(ants.py)` which might be taking up time.

**Comment by colinschoen** [comment]
What browser/OS are you on. I am running a fresh copy of your fork of the GUI and the project and not able to make any state calls. You have everything pushed right?

NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8000/ajax/fetch/state'.

**Comment by msohcw** [comment]
That's very odd. I git clone'd my repo, then copied in ants/*.py except gui.py and state.py, and it works fine. I'm on Ubuntu, tested against Chrome/Firefox. Do you need me to upload the rest of the .py s?

**Comment by colinschoen** [comment]
Can you shoot me an archive of your proj directory with the updated GUI to cschoen [at] berkeley.edu. I'll see if I can find any oddities.

**Comment by msohcw** [comment]
Done. I tar'd up a working copy with the project files and updated gui.py and assets/app.js.

**Comment by msohcw** [comment]
Hmm I think I managed to replicate the error. It seems to be a small timing bug where the player clicks 'Start game', and a POST request is made to the server to start and to get the state, but the server isn't ready yet and causes the request to fail. I added an initialised flag so that it keeps trying to get the state when it is unitialised and only throws an error when there's a network error despite it having been previously initialised.

**Comment by colinschoen** [comment]
`setTimeout(gui.get_gameState(async), 500)`

Can't find variable async line 111.

**Comment by colinschoen** [comment]
Excellent work! Thank you.

**Pull request merged**
